eTicketsUI/Controllers/ActorController.cs
using eTicket.Domain.Entities;
using eTickets.Application.Core.Request;
using eTickets.Application.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace eTickets.UI.Controllers
{
    public class ActorController : Controller
    {
        private readonly IActorService _actorService;

        public ActorController(IActorService actorService)
        {
            _actorService = actorService;
        }



        public async Task<IActionResult> Index()
        {
            var actors = await _actorService.GetAllActors();
            return View(actors);
        }
        public async Task<IActionResult> Detail(int id)
        {
            var actor = await _actorService.GetActorById(id);
            return View(actor);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var actor = await _actorService.GetActorById(id);
            return View(actor);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, ActorReq newActor)
        {
            var actor = await _actorService.GetActorById(id);
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            actor = await _actorService.UpdateActor(id, newActor);
            return View(actor);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ActorReq actor)
        {
            if (ModelState.IsValid)
            {
                var newActor = await _actorService.AddActor(actor);
                return RedirectToAction(nameof(Index));
            }
            
            return View();
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            await _actorService.DeleteActor(id);
            return Ok();
        }
    }
}

eTicketsUI/Controllers/CinemaController.cs
using eTicket.Domain.Entities;
using eTickets.Application.Core.Request;
using eTickets.Application.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace eTickets.UI.Controllers
{
    public class CinemaController : Controller
    {
        private readonly ICinemaService _cinemaService;

        public CinemaController(ICinemaService cinemaService)
        {
            _cinemaService = cinemaService;
        }

        public async Task<IActionResult> Index()
        {
            var cinemas = await _cinemaService.GetAllCinemas();
            return View(cinemas);
        }

        public async Task<IActionResult> Detail(int id)
        {
            var cinema = await _cinemaService.GetCinema(id);
            return View(cinema);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var cinema = await _cinemaService.GetCinema(id);
            return View(cinema);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, CinemaReq newCinema)
            
        {
            var cinema = await _cinemaService.GetCinema(id);
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            cinema = await _cinemaService.UpdateCinema(id,newCinema);
            return View(cinema);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CinemaReq newCinema)
        {
            if (ModelState.IsValid)
            {
                await _cinemaService.AddCinema(newCinema);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            await _cinemaService.DeleteCinema(id);
            return Ok();
        }
    }
}

eTicketsUI/Controllers/MovieController.cs
using eTickets.Application.Core.Dtos;
using eTickets.Application.Core.Request;
using eTickets.Application.Interfaces;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace eTickets.UI.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IActorService _actorService;
        private readonly IProducerService _producerService;
        private readonly ICinemaService _cinemaService;

        public MovieController(IMovieService movieService, IActorService actorService, IProducerService producerService, ICinemaService cinemaService)
        {
            _movieService = movieService;
            _actorService = actorService;
            _producerService = producerService;
            _cinemaService = cinemaService;
        }

        public async Task<IActionResult> Index(string? searchString = null)
        {
            var movies = !String.IsNullOrEmpty(searchString) ? await _movieService.GetAllMovies(searchString) : await _movieService.GetAllMovies();
            return View(movies);
        }
        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
           var movie = await _movieService.GetMovieDetail(id); 
           return View(movie);
        }
        [HttpGet]
        public  async Task<IActionResult> Create() {
            var actors = await _actorService.GetAllActors();
            var producers = await _producerService.GetAllProducers();
            var cinemas = await _cinemaService.GetAllCinemas();
            ViewBag.Actors = new SelectList(actors, "Id", "FullName");
            ViewBag.Producers = new SelectList(producers, "Id", "FullName");
            ViewBag.Cinemas = new SelectList(cinemas, "Id", "Name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MovieReq req)
        {
            if(!ModelState.IsValid)
            {
                var actors = await _actorService.GetAllActors();
                var producers = await _producerService.GetAllProducers();
                var cinemas = await _cinemaService.GetAllCinemas();
                ViewBag.Actors = new SelectList(actors, "Id", "FullName");
                ViewBag.Producers = new SelectList(producers, "Id", "FullName");
                ViewBag.Cinemas = new SelectList(cinemas, "Id", "Name");
            
                return View();   
            }
            var newMovie = await _movieService.CreateMovie(req);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var movie = await _movieService.GetMovieDetail(id);
            movie.ActorIds = movie.Actors.Select(a => a.Id).ToList();
            var actors = await _actorService.GetAllActors();
            var producers = await _producerService.GetAllProducers();
            var cinemas = await _cinemaService.GetAllCinemas();
            ViewBag.Actors = new SelectList(actors, "Id", "FullName");
            ViewBag.Producers = new SelectList(producers, "Id", "FullName");
            ViewBag.Cinemas = new SelectList(cinemas, "Id", "Name");
            return View(movie);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, MovieReq req)
        {
            if(!ModelState.IsValid)
            {
                var movie = await _movieService.GetMovieDetail(id);
                movie.ActorIds = movie.Actors.Select(a => a.Id).ToList();
                var actors = await _actorService.GetAllActors();
                var producers = await _producerService.GetAllProducers();
                var cinemas = await _cinemaService.GetAllCinemas();
                ViewBag.Actors = new SelectList(actors, "Id", "FullName");
                ViewBag.Producers = new SelectList(producers, "Id", "FullName");
                ViewBag.Cinemas = new SelectList(cinemas, "Id", "Name");
                return View(movie);
            }
            var updatedMovie = await _movieService.UpdateMovie(id, req);
            return RedirectToAction(nameof(Index));
            
            
        }

    }
}

eTicketsUI/Controllers/ProducerController.cs
using eTicket.Domain.Entities;
using eTickets.Application.Core.Request;
using eTickets.Application.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace eTickets.UI.Controllers
{
    public class ProducerController : Controller
    {
        private readonly IProducerService _producerService;

        public ProducerController(IProducerService producerService)
        {
            _producerService = producerService;
        }

        public async Task<IActionResult> Index()
        {
            var producers = await _producerService.GetAllProducers();
            return View(producers);
        }
        public async Task<IActionResult> Detail(int id)
        {
            var producer = await _producerService.GetProducerById(id);
            return View(producer);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var producer = await _producerService.GetProducerById(id);
            return View(producer);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProducerReq newProducer)
        {
            var producer = await _producerService.GetProducerById(id);
            producer = await _producerService.UpdateProducer(id, newProducer);
            return View(producer);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProducerReq producer)
        {
            if (ModelState.IsValid)
            {
                await _producerService.AddProducer(producer);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            await _producerService.DeleteProducer(id);
            return Ok();
        }
    }
}

eTicketsUI/Views/Shared/_CreateItem.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div style="position: fixed; right: 25px; bottom: 25px; z-index:999;" class="text-white">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i> Add New
    </a>
</div>

eTicketsUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eTicketsUI.styles.css" asp-append-version="true" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <script src="~/popper.js/umd/popper.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Movie" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index"><i class="bi bi-film"></i> Movies</a>
                        </li>


                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Cinema" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                    <a class="dropdown-item" asp-controller="Producer" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                    <a class="dropdown-item" asp-controller="Actor" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                                </div>
                            </li>
                        

                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Movie" asp-action="Index" style="padding-right: 25px;">
                        <div class="input-group">
                            <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                        </div>
                    </form>

 
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - eTickets
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
	
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>